version: '3.1'

networks:
  adop_network:
    driver: overlay
    
services:
  portainer:
    image: portainer
    deploy:
      replicas: 1
    networks:
      - adop_network
    ports:
      - "9000:9000"
 
  jenkins:
    image: jenkins
    deploy:
      replicas: 1
    networks:
      - adop_network
    ports:
      - "8080:8080"
      
  sonarqube:
    image: sonarqube
    deploy:
      replicas: 1
    networks:
      - adop_network
    ports:
      - "9092:9092"