version: '3'

networks:
  adop_network:
    driver: overlay

volumes:
  portainer_data:
    
services:
  portainer:
    image: portainer/portainer
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer_data:/data
    deploy:
      replicas: 1
      placement:
        constraints: [node.role == manager]
    networks:
      - adop_network
    ports:
      - "80:9000"
 
  jenkins:
    image: jenkins
    deploy:
      replicas: 1
    networks:
      - adop_network
    ports:
      - "8080:8080"
      
  sonarqube:
    image: sonarqube
    deploy:
      replicas: 1
    networks:
      - adop_network
    ports:
      - "9092:9092"
      - "9000:9000"