version: '3.2'

networks:
  adop_network:
    driver: overlay

volumes:
  portainer_data:
    
services:
  portainer:
    image: portainer
    volumes:
      - type: volume
        source: portainer_data
        target: /data
        volume:
          nocopy: false
      - type: bind
        source: //var/run/docker.sock
        target: /var/run/docker.sock
    deploy:
      replicas: 1
    networks:
      - adop_network
    ports:
      - "80:9000"
 
  jenkins:
    image: jenkins
    deploy:
      replicas: 1
    networks:
      - adop_network
    ports:
      - "8080:8080"
      
  sonarqube:
    image: sonarqube
    deploy:
      replicas: 1
    networks:
      - adop_network
    ports:
      - "9092:9092"
      - "9000:9000"