---
- name: Pre-requisite configuration and Docker Engine setup
  hosts: all
  become_user: root
  become: true

  roles:
    - docker

- name: Setup Swarm cluster on Management nodes
  hosts: manager
  become_user: root
  become: true

  roles:
    - swarm-manager
    
- name: Setup Swarm cluster on Workers
  hosts: worker
  become_user: root
  become: true

  roles:
    - swarm-workers
   
- name: Check if the nodes are active - manager
  hosts: manager
  become_user: root
  become: true
  
  roles:
    - docker-compose