- name: install wget
  yum:
    name: wget
    state: latest

- name: Copy docker-ce-selinux into home directory
  copy:
    src: ../files/docker-ce-selinux-17.03.2.ce-1.el7.centos.noarch.rpm 
    dest: /home/ec2-user/docker-ce-selinux-17.03.2.ce-1.el7.centos.noarch.rpm

- name: Copy docker-ce-centos into home directory
  copy:
    src: ../files/docker-ce-17.03.2.ce-1.el7.centos.x86_64.rpm 
    dest: /home/ec2-user/docker-ce-17.03.2.ce-1.el7.centos.x86_64.rpm   

- name: install docker-ce-selinux
  yum:
    name: /home/ec2-user/docker-ce-selinux-17.03.2.ce-1.el7.centos.noarch.rpm 
    state: present
    
- name: install docker-ce-centos
  yum:
    name: /home/ec2-user/docker-ce-17.03.2.ce-1.el7.centos.x86_64.rpm
    state: present
    
- name: Start docker service, if not running
  service:
    name: docker
    state: started
    enabled: yes
    
    
  
