- name: Join Swarm Cluster
  vars:
    token: "{{ hostvars[groups['manager'][0]]['worker_token']['stdout'] }}"
    manager1: "{{ hostvars[groups['manager'][0]]['inventory_hostname'] }}"
   
- name: Join Swarm Cluster as Workers
  command: docker swarm join --token {{ token }} {{ manager1 }}:2377
  register: workers
      
- name: Show Results
  debug: var=workers.stdout
  
- name: Show Errors
  debug: var=workers.stderr

