- name: Check if Swarm was created
  shell: "docker info | grep 'Swarm: active' | wc -l"
  register: swarm_status

- name: Join Swarm Cluster
  shell: "docker swarm join --token {{ hostvars['manager']['worker_token']['stdout'] }} {{ hostvars[groups['manager'][0]]['inventory_hostname'] }}:2377"
  when: swarm_status.stdout!="1"
  retries: 3
  delay: 20
