- name: Check if Swarm was created
  shell: "docker info | grep 'Swarm: active' | wc -l"
  register: swarm_status
  
- name: Show Swarm Statuss Token
  debug: var=swarm_status.stdout

- name: Init a new swarm
  command: docker swarm init --advertise-addr {{ inventory_hostname }}
  when: swarm_status.stdout!="1"

- name: Get Worker Token
  command: docker swarm join-token worker -q
  register: worker_token
  
- name: Show Worker Token
  debug: var=worker_token.stdout
  
- name: Join Swarm Cluster
  vars:
    token: "{{ hostvars[groups['manager'][0]]['worker_token']['stdout'] }}"
    manager1: "{{ hostvars[groups['manager'][0]]['inventory_hostname'] }}"
  tasks:
    - name: Join Swarm Cluster as Workers
      command: docker swarm join --token {{ token }} {{ manager1 }}:2377
      register: worker
      
    - name: Show Results
      debug: var=worker.stdout

    - name: Show Errors
      debug: var=worker.stderr

