- name: Check if Swarm was created
  shell: "docker info | grep 'Swarm: active' | wc -l"
  register: swarm_status
  
- name: Show Swarm Statuss Token
  debug: var=swarm_status.stdout

- name: Init a new swarm
  command: docker swarm init --advertise-addr {{ inventory_hostname }}
  when: swarm_status.stdout!="1"

- name: Get Master Token
  command: docker swarm join-token master -q
  register: master_token
  
- name: Show Master Token
  debug: var=master_token.stdout

